apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  type: NodePort
  selector:
    run: nginx
  ports:
  - name: http
    port: 80
    nodePort: 30000
    protocol: TCP
  - name: https
    port: 443
    nodePort: 30001
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginx-tls-secret
      - name: configmap-volume
        configMap:
          name: nginx-conf
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d/
          name: configmap-volume
